name: screencast_difference_game
author: rchavarria
description: Screencast resolviendo un problema de solveet.com mediante técnicas aprendidas de los screencast de Carlos Blé
homepage: http://rchavarria.github.io
